### ISSUE TITLE
May I use your code for my project?

### ISSUE THREAD

**Issue by developomp** [aurzen/pinbot#2]
I wanted to use your code for [my project](https://github.com/developomp/discord-warbrokers-llama) but your repo didn't have a license. After a bit of searching, I found out that all rights are reserved for the owner of a project with no specified license and for me to use your code I have to ask the owner's explicit permission.
May I use your code for my project and license it under the MIT license?

**Comment by Zenith00** [comment]
I've added a MIT license.
Feel free to use the code as you wish in line with that!
